return {
	title = "Valjas kleine Abenteuer",
	["menu.start"] = "Start",
	["menu.language"] = "Sprache",
	["menu.quit"] = "Beenden",
	["pause.continue"] = "Weiter",
	["pause.restart"] = "Neu starten",
	["pause.main_menu"] = "Menü",
	["garden.instruction"] = "Geh zur Blume und drücke die Taste.",
	["garden.interaction"] = "Hallo!",
	["garden.prompt"] = "Drücke A",
	["language.ru"] = "Русский",
	["language.de"] = "Deutsch",
	["country.germany"] = "Deutschland",
	["country.russia"] = "Russland",
	["country.india"] = "Indien",
	["country.japan"] = "Japan",
	["country.brazil"] = "Brasilien",
	["country.usa"] = "USA",
	["country.australia"] = "Australien",
	["country.egypt"] = "Ägypten",
	["flight.cycle_complete"] = "Super! Alle Aufgaben geschafft!",
}
