return {
	title = "Маленькие приключения Вали",
	["menu.start"] = "Старт",
	["menu.language"] = "Язык",
	["menu.quit"] = "Выход",
	["pause.continue"] = "Дальше",
	["pause.restart"] = "Сначала",
	["pause.main_menu"] = "Меню",
	["language.ru"] = "Русский",
	["language.de"] = "Deutsch",
	["country.germany"] = "Германия",
	["country.russia"] = "Россия",
	["country.india"] = "Индия",
	["country.japan"] = "Япония",
	["country.brazil"] = "Бразилия",
	["country.usa"] = "США",
	["country.australia"] = "Австралия",
	["country.egypt"] = "Египет",
	["flight.cycle_complete"] = "Молодец! Все задания выполнены!",
}
