-- Renderer-independent country lookup from the ID mask.
--
-- The game keeps storing positions as {lat, lon} and never needs to know how
-- the globe is drawn. This module turns a lat/lon into a country id by sampling
-- the flat-colored equirectangular mask (assets/globe/country_ids.png) on the
-- CPU: no GPU readback, no shader dependency. The color -> country table comes
-- from content/regions.lua (both generated by scripts/gen-globe-assets.py from
-- the same Natural Earth data, so mask and table always agree).
--
-- Two constructors:
--   GlobeRegions.new(path, regions)          -- loads the PNG via LOVE
--   GlobeRegions.fromImageData(img, regions) -- inject any object exposing
--                                               getWidth/getHeight/getPixel,
--                                               so the lookup math is unit-
--                                               testable without LOVE.
--
-- This is layered ON TOP of the existing World:countryAt (great-circle region
-- circles for the 5 playable countries). Gameplay/recognition stay on World;
-- GlobeRegions is for the exploration label and highlighting across all ~200
-- Natural Earth countries.

local GlobeRegions = {}
GlobeRegions.__index = GlobeRegions

-- Wrap longitude into [-180, 180) so the dateline samples the correct column
-- instead of clamping to the edge.
local function normalizeLon(lon)
	lon = (lon + 180) % 360
	if lon < 0 then
		lon = lon + 360
	end
	return lon - 180
end

---Build from an already-loaded image-data-like object. `img` must answer
---getWidth(), getHeight(), and getPixel(x, y) -> r, g, b (, a) in 0..1 floats
---(LOVE 11 ImageData semantics).
---@param img table
---@param regions table the table returned by content/regions.lua { byColor, list }
---@return table
function GlobeRegions.fromImageData(img, regions)
	local self = setmetatable({}, GlobeRegions)
	self.img = img
	self.w = img:getWidth()
	self.h = img:getHeight()
	self.byColor = regions.byColor
	self.list = regions.list
	-- Index by ISO-2 code so callers (e.g. the Flight Map's game countries) can
	-- fetch a country's flat mask color without knowing the Natural Earth slug.
	self.byIso = {}
	for _, r in ipairs(regions.list) do
		if r.iso and r.iso ~= "-" then
			self.byIso[r.iso] = r
		end
	end
	return self
end

---Load the mask PNG through LOVE (needs a graphics/image context).
---@param path string
---@param regions table
---@return table
function GlobeRegions.new(path, regions)
	local imageData = love.image.newImageData(path)
	return GlobeRegions.fromImageData(imageData, regions)
end

-- Equirectangular pixel for a lat/lon: lon -180..180 -> x 0..w, lat 90..-90 ->
-- y 0..h. Clamped to the last valid pixel.
function GlobeRegions:pixelFor(lat, lon)
	lon = normalizeLon(lon)
	local u = (lon + 180) / 360
	local v = (90 - lat) / 180
	local px = math.floor(u * self.w)
	local py = math.floor(v * self.h)
	if px < 0 then
		px = 0
	elseif px > self.w - 1 then
		px = self.w - 1
	end
	if py < 0 then
		py = 0
	elseif py > self.h - 1 then
		py = self.h - 1
	end
	return px, py
end

---The Natural Earth country region record at (lat, lon), or nil over ocean.
---Returns the full entry { id, name, name_ru, name_de, iso, iso3, continent,
---color }.
---@param lat number
---@param lon number
---@return table|nil
function GlobeRegions:regionAt(lat, lon)
	local px, py = self:pixelFor(lat, lon)
	local r, g, b = self.img:getPixel(px, py)
	-- LOVE 11 getPixel returns 0..1 floats; scale to 0..255 ints and round so
	-- the key matches the flat colors baked into the mask exactly.
	local key = math.floor(r * 255 + 0.5)
		.. ","
		.. math.floor(g * 255 + 0.5)
		.. ","
		.. math.floor(b * 255 + 0.5)
	return self.byColor[key]
end

---Just the country id at (lat, lon), or nil over ocean.
---@param lat number
---@param lon number
---@return string|nil
function GlobeRegions:countryAt(lat, lon)
	local region = self:regionAt(lat, lon)
	return region and region.id or nil
end

---The flat id-mask color ({r,g,b} 0..255) for an ISO-2 code, or nil if the
---mask has no such country. Used to drive shader highlights by ISO.
---@param iso string
---@return table|nil
function GlobeRegions:colorForIso(iso)
	local region = self.byIso[iso]
	return region and region.color or nil
end

return GlobeRegions
